Work
Mwapsam/capstone-m1 pull request #2
Opened 2021-12-23 20:18 UTC by Mwapsam

- Configure Linters (Webhint, stylelint, lighthouse & eslint)
- Add html, css & JavaScript file
- Fix linter errors
- Save to git pages
- Update Readme file

2021-12-23 21:02 UTC, leolpaz requested changes
Hi @Mwapsam , 

You've done an amazing job so far, I'd like to highlight the following:
- Linters is passing
- Good video

Some issues need to be resolved before your approval, but you're almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 21:02 UTC, leolpaz commented on about.html
> +              experimental forms of democratic governance.
- [ ] To comply with the design, kindly make sure that both footers have the same text content

2021-12-23 21:02 UTC, leolpaz commented on assets/css/main.css
> +    height: 300px;
- [ ] The footer on both pages should look the same, currently, the one on the about page is a lot taller than the one on the home page, kindly fix that
About page
![image](https://user-images.githubusercontent.com/73140461/147290224-ab5eb19f-bdcc-4d67-bcc8-50505bb8978e.png)
Home page
![image](https://user-images.githubusercontent.com/73140461/147290267-83708558-8cd7-4e00-82b6-348744e63aae.png)



- [ ] The footer on the mobile version in the about page should have a light background, kindly add that
![image](https://user-images.githubusercontent.com/73140461/147290122-8c8b79e1-e579-4b34-8595-00a7d21fd805.png)

2021-12-23 21:02 UTC, leolpaz commented on assets/css/desktop.css
> +  }
- [x] Kindly fix the spacing between the h3 and the h1
Your page:
![image](https://user-images.githubusercontent.com/73140461/147290703-cab74843-7eac-41c0-8dea-2f9634d82969.png)
Design:
![image](https://user-images.githubusercontent.com/73140461/147290728-17af66f1-1f45-43e0-974b-f7114eb959ca.png)

2021-12-24 06:16 UTC, julie-ify approved these changes
## Hi @Mwapsam, 

# Highlights
- Good job implementing the required changes from the previous reviewer ✔️ 
- Good video presentation ✔️ 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved emoji](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-27 05:26 UTC, merged